DBCC CHECKIDENT ('[dbo].[Domaines]', RESEED, 227);
-- The next inserted row will be 1000 (RESEED value + 1)
INSERT INTO Domaines (Nomdomaine) VALUES
('Informatique'),
('Développement logiciel'),
('Cybersécurité'),
('Intelligence artificielle'),
('Data Science'),
('Analyse de données'),
('Cloud Computing'),
('Ingénierie réseau'),
('Administration système'),
('Développement web'),
('Développement mobile'),
('Gestion de projet IT'),
('Support technique'),
('Sécurité informatique'),

('Médecine'),
('Chirurgie'),
('Médecine générale'),
('Pédiatrie'),
('Cardiologie'),
('Neurologie'),
('Oncologie'),
('Gynécologie'),
('Ophtalmologie'),
('Dentisterie'),
('Psychiatrie'),
('Kinésithérapie'),
('Pharmacie'),
('Radiologie'),
('Anesthésie'),

('Éducation'),
('Enseignement primaire'),
('Enseignement secondaire'),
('Université'),
('Formation professionnelle'),
('Éducation spécialisée'),
('Recherche académique'),
('Pédagogie'),

('Ingénierie'),
('Ingénierie mécanique'),
('Ingénierie électrique'),
('Ingénierie civile'),
('Ingénierie industrielle'),
('Ingénierie aérospatiale'),
('Ingénierie chimique'),
('Ingénierie biomédicale'),
('Ingénierie environnementale'),
('Robotique'),

('Finance'),
('Banque'),
('Assurance'),
('Comptabilité'),
('Analyse financière'),
('Gestion de patrimoine'),
('Bourse et trading'),
('Audit'),

('Marketing'),
('Marketing digital'),
('Publicité'),
('Relations publiques'),
('SEO/SEA'),
('Community Management'),
('Stratégie marketing'),
('Branding'),

('Droit'),
('Droit pénal'),
('Droit civil'),
('Droit des affaires'),
('Droit du travail'),
('Droit international'),
('Notariat'),
('Avocat'),
('Juge'),

('Agriculture'),
('Agronomie'),
('Élevage'),
('Pêche'),
('Sylviculture'),
('Viticulture'),
('Agroalimentaire'),

('Art & Design'),
('Architecture'),
('Design graphique'),
('Design d’intérieur'),
('Illustration'),
('Peinture'),
('Sculpture'),
('Animation 3D'),
('Photographie'),
('Cinéma'),

('Commerce'),
('E-commerce'),
('Vente'),
('Achats'),
('Logistique'),
('Import-export'),
('Distribution'),

('Transport & Logistique'),
('Transport routier'),
('Transport ferroviaire'),
('Transport aérien'),
('Transport maritime'),
('Supply Chain'),
('Gestion des stocks'),
('Entreposage'),

('Construction'),
('Maçonnerie'),
('Plomberie'),
('Électricité bâtiment'),
('Charpenterie'),
('Menuiserie'),
('Architecture d’intérieur'),
('Urbanisme'),

('Tourisme'),
('Voyages'),
('Guides touristiques'),
('Agences de voyages'),
('Hôtellerie'),
('Restauration'),
('Animation touristique'),

('Sciences'),
('Physique'),
('Chimie'),
('Biologie'),
('Mathématiques'),
('Astronomie'),
('Sciences sociales'),
('Géologie'),
('Météorologie'),

('Pharmaceutique'),
('Recherche en pharmacie'),
('Production pharmaceutique'),
('Pharmacovigilance'),
('Biotechnologie pharmaceutique'),

('Journalisme'),
('Presse écrite'),
('Télévision'),
('Radio'),
('Webjournalisme'),
('Rédaction technique'),
('Édition'),

('Mode'),
('Stylisme'),
('Modélisme'),
('Haute couture'),
('Accessoiriste'),

('Musique'),
('Chant'),
('Composition musicale'),
('Production musicale'),
('Mixage & Mastering'),
('DJing'),

('Sport'),
('Entraînement sportif'),
('Préparation physique'),
('Sport professionnel'),
('Éducation sportive'),

('Énergie'),
('Pétrole & Gaz'),
('Énergies renouvelables'),
('Nucléaire'),
('Hydroélectricité'),

('Télécommunications'),
('Réseaux mobiles'),
('Fibre optique'),
('Satellite'),

('Aérospatiale'),
('Conception aéronautique'),
('Pilotage'),
('Maintenance aéronautique'),
('Astrophysique'),

('Automobile'),
('Mécanique automobile'),
('Conception automobile'),
('Tuning & Personnalisation'),

('Biotechnologie'),
('Recherche en biotechnologie'),
('Génétique'),
('Biologie synthétique'),

('Restauration'),
('Cuisine'),
('Pâtisserie'),
('Service en salle'),
('Œnologie'),

('Hôtellerie'),
('Réception'),
('Gestion hôtelière'),
('Conciergerie'),

('Immobilier'),
('Agent immobilier'),
('Gestion locative'),
('Promoteur immobilier'),

('Assistance sociale'),
('Psychologie'),
('Travail social'),
('Coaching de vie'),

('Gestion & Management'),
('Entrepreneuriat'),
('Gestion des ressources humaines'),
('Consulting'),
('Coaching professionnel'),

('Sécurité & Défense'),
('Police'),
('Armée'),
('Sécurité privée'),
('Pompiers'),

('Divertissement'),
('Jeux vidéo'),
('Streaming'),
('YouTube'),
('Twitch'),
('Animation de spectacles'),
('Événementiel'),

('Développement Durable'),
('Économie circulaire'),
('Énergies renouvelables'),
('Gestion des déchets'),
('Éco-construction'),

('Crypto & Blockchain'),
('Développement blockchain'),
('Trading crypto'),
('NFT & Web3'),

('Événementiel'),
('Organisation d’événements'),
('Wedding planning'),
('Gestion de festivals');

